app/routes.py
from flask import Blueprint, render_template, request, session, redirect, url_for, abort

from .utils.messages import info_message, success_message, warning_message, error_message
from .utils.sessions import login_required, admin_required, add_user_to_session, get_user_id
from .utils import users as u
from .utils import recipies as r
from .utils import cooking_levels as cl
from .utils import food_categories as fc
from .utils import types_of_food as tof

app = Blueprint('main', __name__, template_folder='templates')


@app.route('/')
def index():
    food_categories = fc.get_food_categories_list()
    types_of_food = tof.get_types_of_food_list()
    return render_template('index.html',
                           recipes=r.get_recipes_list(True),
                           daily_recipe=r.get_daily_recipe(),
                           food_categories=food_categories,
                           types_of_food=types_of_food)


@app.route('/o-nas')
def about_us():
    return render_template('/o_nas.html')


@app.route('/logowanie', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('logowanie.html')

    username = request.form.get('username')
    password = request.form.get('password')

    if any(v is None for v in [username, password]):
        return render_template('logowanie.html', msg=error_message('Nie wypełniono wszystkich pól'))

    if u.authenticate_user(username, password):
        add_user_to_session(username)
        return redirect(url_for('.index'))
    else:
        return render_template('logowanie.html', msg=error_message('Podano błędny login i/lub hasło'))


@app.route('/wyloguj')
@login_required
def logout():
    session.clear()
    return redirect(url_for('.index'))


@app.route('/rejestracja', methods=['GET', 'POST'])
def register():
    cooking_levels = cl.get_cooking_levels()
    if request.method == 'GET':
        return render_template('rejestracja.html', cooking_levels=cooking_levels)

    user_login = request.form.get('username')
    user_sex = request.form.get('sex')
    user_cooking_level = request.form.get('cooking_level')
    user_password1 = request.form.get('password1')
    user_password2 = request.form.get('password2')

    if any(v is None for v in [user_login, user_sex, user_cooking_level, user_password1, user_password2]):
        return render_template('rejestracja.html',
                               msg=error_message('Nie wypełniono wszystkich pól'),
                               cooking_levels=cooking_levels)

    if u.exists(user_login):
        return render_template('rejestracja.html',
                               msg=error_message('Ta nazwa użytkownika jest już zajęta'),
                               cooking_levels=cooking_levels)

    if not u.validate_username(user_login):
        msg = 'Nazwa użytkownika może składać się jedynie z liter i cyfr, od 4 do 12 znaków'
        return render_template('rejestracja.html',
                               msg=error_message(msg),
                               cooking_levels=cooking_levels)

    if user_password1 != user_password2:
        return render_template('rejestracja.html',
                               msg=error_message('Podane hasła nie są takie same'),
                               cooking_levels=cooking_levels)

    if not u.validate_passwords(user_password1, user_password2):
        return render_template('rejestracja.html',
                               msg=error_message('Podane hasło nie spełnia wymogów bezpieczeństwa'),
                               cooking_levels=cooking_levels)

    u.new_user(user_login, user_password1, user_sex, user_cooking_level)
    add_user_to_session(user_login)
    return redirect(url_for('.index'))


@app.route('/profil', methods=['GET', 'POST'])
@login_required
def user_profile():
    if request.method == 'GET':
        return render_template('profil.html')

    new_password1 = request.form.get('password1')
    new_password2 = request.form.get('password2')

    if any(v is None for v in [new_password1, new_password2]):
        return render_template('profil.html', msg=error_message('Nie wypełniono wszystkich pól'))

    if new_password1 != new_password2:
        return render_template('profil.html', msg=error_message('Podane hasła nie są takie same'))

    if not u.validate_passwords(new_password1, new_password2):
        return render_template('profil.html', msg=error_message('Podane hasło nie spełnia wymogów bezpieczeństwa'))
    return render_template('profil.html', msg=success_message('Hasło zaktualizowane'))


@app.route('/admin')
@login_required
@admin_required
def admin():
    return render_template('administrator.html',
                           recipes_to_check=r.get_recipes_list(False),
                           users=u.get_all_users())


@app.route('/ustaw-role/<int:user_id>/administrator')
@login_required
@admin_required
def set_admin_role(user_id):
    if user_id != get_user_id():
        u.set_admin(user_id)
    return redirect(url_for('.admin'))


@app.route('/ustaw-role/<int:user_id>/user')
@login_required
@admin_required
def set_user_role(user_id):
    if user_id != get_user_id():
        u.set_user(user_id)
    return redirect(url_for('.admin'))


@app.route('/usun/uzytkownik/<int:user_id>')
@login_required
@admin_required
def delete_user(user_id):
    if user_id != get_user_id():
        u.delete_user(user_id)
    return redirect(url_for('.admin'))


@app.route('/dodaj-przepis', methods=['GET', 'POST'])
@login_required
def new_recipe():
    food_categories = fc.get_food_categories_list()
    types_of_food = tof.get_types_of_food_list()

    if request.method == 'GET':
        return render_template('dodaj_przepis.html',
                               food_categories=food_categories,
                               types_of_food=types_of_food)

    recipe_name = request.form.get('name')
    recipe_type = request.form.get('type')
    recipe_food_category = request.form.get('category')
    recipe_time_required = request.form.get('time')
    recipe_description = request.form.get('description')

    if any(v is None or v == '' for v in [recipe_name, recipe_type, recipe_food_category, recipe_time_required,
                                          recipe_description]):
        return render_template('dodaj_przepis.html',
                               msg=error_message('Nie wypełniono wszystkich pól'),
                               food_categories=food_categories,
                               types_of_food=types_of_food)

    try:
        recipe_time_required = recipe_time_required.replace(',', '.')
        float(recipe_time_required)
    except (TypeError, ValueError):
        return render_template('dodaj_przepis.html',
                               msg=error_message('Czas przygotowania musi być liczbą'),
                               food_categories=food_categories,
                               types_of_food=types_of_food)

    if not r.validate_name(recipe_name):
        msg = 'Podano błędną nazwę przepisu. Powinna zawierać od 5 do 75 znaków oraz wybrane znaki specjalne (!:.,-)'
        return render_template('dodaj_przepis.html',
                               msg=error_message(msg),
                               food_categories=food_categories,
                               types_of_food=types_of_food)

    if r.recipe_exists(recipe_name):
        return render_template('dodaj_przepis.html',
                               msg=error_message('Przepis o takiej nazwie już istnieje'),
                               food_categories=food_categories,
                               types_of_food=types_of_food)
    if not 50 < len(recipe_description) < 5000:
        return render_template('dodaj_przepis.html',
                               msg=error_message('Opis powinien mieć od 50 do 5000 znaków'),
                               food_categories=food_categories,
                               types_of_food=types_of_food)

    r.new_recipe(get_user_id(), recipe_name, recipe_type, recipe_food_category, recipe_description,
                 recipe_time_required)
    msg = 'Przepis pomyślnie dodano, czeka on na zatwierdzenie przez administratora'
    return render_template('dodaj_przepis.html',
                           msg=success_message(msg),
                           food_categories=food_categories,
                           types_of_food=types_of_food)


@app.route('/przepis/<int:recipe_id>')
def get_recipe(recipe_id):
    if r.recipe_checked(recipe_id):
        r.add_view(recipe_id)
        return render_template('przepis.html', recipe=r.get_recipe(recipe_id))
    else:
        abort(404)


@app.route('/przepis/<int:recipe_id>/akceptuj')
@login_required
@admin_required
def accept_recipe(recipe_id):
    r.accept_recipe(recipe_id)
    return redirect(url_for('.admin'))


@app.route('/przepis/<int:recipe_id>/odrzuc')
@login_required
@admin_required
def delete_recipe(recipe_id):
    r.delete_recipe(recipe_id)
    return redirect(url_for('.admin'))


@app.route('/szukaj')
def search():
    food_categories = fc.get_food_categories_list()
    types_of_food = tof.get_types_of_food_list()

    query = request.args.get('q')
    type_ = request.args.get('typ')
    if type_ not in ['nazwa', 'typ', 'kategoria']:
        abort(406)
    recipes = r.search_recipes(query, type_, True)
    return render_template('szukaj.html',
                           recipes=recipes,
                           food_categories=food_categories,
                           types_of_food=types_of_food)

app/templates/administrator.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WITKWINTNIE!</title>
  <link rel="stylesheet" href="/static/css/bulma.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

  <style type="text/css">
    .tg {
      border-collapse: collapse;
      border-spacing: 0;
    }

    .tg td {
      border-color: black;
      border-style: solid;
      border-width: 1px;
      font-family: Arial, sans-serif;
      font-size: 14px;
      overflow: hidden;
      padding: 10px 5px;
      word-break: normal;
    }

    .tg th {
      border-color: black;
      border-style: solid;
      border-width: 1px;
      font-family: Arial, sans-serif;
      font-size: 14px;
      font-weight: normal;
      overflow: hidden;
      padding: 10px 5px;
      word-break: normal;
    }
    
    .tg .tg-0lax {
      text-align: left;
      vertical-align: top
    }
  </style>
</head>

<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="image is-64x64">
        <img src="/static/img/logo.png" width=auto height=auto>
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a href="{{ url_for('main.index') }}" class="navbar-item">
          Strona główna
        </a>
        <a href="{{ url_for('main.about_us') }}" class="navbar-item">
          O nas
        </a>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if session.user is defined %}
            {% if session.user.role_name == "Administrator" %}
            <a href="{{ url_for('main.admin') }}" class="button is-success is-outlined">
              Panel Administratora
            </a>
            {% endif %}
            <a href="{{ url_for('main.new_recipe') }}" class="button is-primary is-outlined">
              Dodaj przepis
            </a>
            <a href="{{ url_for('main.user_profile') }}" class="button is-info is-outlined">
              Mój Profil
            </a>
            <a href="{{ url_for('main.logout') }}" class="button is-danger is-outlined">
              Wyloguj
            </a>
            {% else %}
            <a href="{{ url_for('main.register') }}" class="button is-primary">
              <strong>Rejestracja</strong>
            </a>
            <a href="{{ url_for('main.login') }}" class="button is-light">
              Logowanie
              {% endif %}
            </a>

          </div>
        </div>
      </div>
    </div>
  </nav>

  <section class="section">
    <div class="columns is-centered">
      <div class="control">
        {% if recipes_to_check %}
        <table class="table">
          <thead>
            <tr>
              <th class="tg-0lax">Id przepisu</th>
              <!-- <th class="tg-0lax">Id użytkownika</th> -->
              <th class="tg-0lax">Nazwa użytkownika</th>
              <th class="tg-0lax">Nazwa przepisu</th>
              <th class="tg-0lax"><span style="font-weight:400;font-style:normal">Typ</span></th>
              <th class="tg-0lax"><span style="font-weight:400;font-style:normal">Kategoria</span></th>
              <th class="tg-0lax">Wymagany czas</th>
              <th class="tg-0lax">Opis przygotowania</th>
              <th class="tg-0lax"><span style="font-weight:400;font-style:normal">Data utworzenia</span></th>
              <th class="tg-0lax">Zatwierdzić?</th>
            </tr>
          </thead>
          <tbody>
            {% for recipe in recipes_to_check %}
            <tr>
              <td class="tg-0lax">{{ recipe.recipe_id }}</td>
              <!-- <td class="tg-0lax">{{ recipe.user_id }}</td> -->
              <td class="tg-0lax">{{ recipe.username }}</td>
              <td class="tg-0lax">{{ recipe.name }}</td>
              <td class="tg-0lax">{{ recipe.type_of_food }}</td>
              <td class="tg-0lax">{{ recipe.food_category }}</td>
              <td class="tg-0lax">{{ recipe.time_required }} min</td>
              <td class="tg-0lax">{{ recipe.description }}</td>
              <td class="tg-0lax">{{ recipe.creation_date }}</td>
              <td class="tg-0lax">
                <a class="button is-success is-small"
                  href="{{ url_for('main.accept_recipe', recipe_id=recipe.recipe_id) }}">Akceptuj</a>
                <a class="button is-danger is-small"
                  href="{{ url_for('main.delete_recipe', recipe_id=recipe.recipe_id) }}">Odrzuć</a>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        {% else %}
        <p>Brak przepisów do zatwierdzenia</p>
        {% endif %}
        
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>

        <div class="container has-text-centered">
          <p class="title is-3 is-spaced">Użytkownicy:</p>
          <table class="table">
            <thead>
              <tr>
                <th class="tg-0pky">Id</th>
                <th class="tg-0pky"><span style="font-weight:400;font-style:normal">Nazwa użytkownika</span></th>
                <th class="tg-0pky">Data utworzenia konta</th>
                <th class="tg-0pky">Data ostatniego logowania</th>
                <th class="tg-0pky">Rola</th>
                <th class="tg-0pky"><span style="font-weight:400;font-style:normal">Poziom zaawansowania</span></th>
                <th class="tg-0pky">Płeć</th>
                <th class="tg-0pky">Zmiana roli</th>
                <th class="tg-0pky">Usunięcie użytkownika</th>
              </tr>
            </thead>
            <tbody>
              {% for user in users %}
              <tr>
                <td class="tg-0pky">{{ user.user_id }}</td>
                <td class="tg-0pky">{{ user.username }}</td>
                <td class="tg-0pky">{{ user.creation_date }}</td>
                <td class="tg-0pky">{{ user.last_login_date }}</td>
                <td class="tg-0pky">{{ user.role }}</td>
                <td class="tg-0pky">{{ user.cooking_level }}</td>
                <td class="tg-0pky">{{ user.sex }}</td>
                <td class="tg-0pky">
                  <div class="columns">
                    <div class="column">
                      <a class="button is-success is-small"
                        href="{{ url_for('main.set_user_role', user_id=user.user_id) }}">Użytkownik</a>
                      <div class="columns is-mobile">
                        <div class="column">
                          <a class="button is-danger is-small"
                            href="{{ url_for('main.set_admin_role', user_id=user.user_id) }}">Administrator</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
                <td>
                  <a class="button is-danger is-small"
                    href="{{ url_for('main.delete_user', user_id=user.user_id) }}">
                    Usuń użytkownika</a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </section>

<!--Stopka-->
  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>WITKWINTNIE DANIE</strong>
      <p>Jakub Kulikowski, Adam Żywica, Adam Wasilewski, Piotr Sumiński, Piotr Król. </p>
      </br>
      <p>Projekt dostępny na,
        <a href="https://github.com/a-was/kuchniowy-raj">githubie</a>.
      </p>
      </p>
    </div>
  </footer>
</body>

</html>

app/templates/index.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>WITKWINTNIE!</title>
  <link rel="stylesheet" href="/static/css/bulma.css">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
</head>

<body>

  <!--Header-->
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="image is-64x64">
        <img src="/static/img/logo.png" width=auto height=auto>
      </a>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
        data-target="navbarBasicExample">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
        <a href="{{ url_for('main.index') }}" class="navbar-item">
          Strona główna
        </a>

        <a href="{{ url_for('main.about_us') }}" class="navbar-item">
          O nas
        </a>

      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">


            {% if session.user is defined %}

            {% if session.user.role_name == "Administrator" %}
            <a href="{{ url_for('main.admin') }}" class="button is-success is-outlined">
              Panel Administratora
            </a>
            {% endif %}
            <a href="{{ url_for('main.new_recipe') }}" class="button is-primary is-outlined">
              Dodaj przepis
            </a>
            <a href="{{ url_for('main.user_profile') }}" class="button is-info is-outlined">
              Mój Profil
            </a>
            <a href="{{ url_for('main.logout') }}" class="button is-danger is-outlined">
              Wyloguj
            </a>
            {% else %}
            <a href="{{ url_for('main.register') }}" class="button is-primary">
              <strong>Rejestracja</strong>
            </a>
            <a href="{{ url_for('main.login') }}" class="button is-light">
              Logowanie
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div class="hero">
    <img src="/static/img/index_background.png" />




    <!--przepisy-->

    <div class="columns">
      <div class="column">
        <article class="panel is-primary">

          <div class="panel-heading">
            <div class="media">
              <div class="media-left">
                Przepisy
              </div>
              <div class="media-content">
              </div>
              <div class="media-right">
              </div>
            </div>
          </div>

          <!-- przerwa dla lepszego wyglądu-->
          <div class="panel-block">
            <div class="tabs is-centered">
            </div>
          </div>

          {% for recipe in recipes %}
          <article class="media">
            <figure class="media-left">
              <p class="image is-96x96">
                <img src="/static/img/logo.png">
              </p>
            </figure>
            <div class="media-content recipe">
              <div class="content">
                <p>
                  <a href="{{ url_for('main.get_recipe', recipe_id=recipe.recipe_id) }}"
                    style="color: inherit"><strong>{{ recipe.name }}</strong>
                  </a> {% if recipe.username is none %}<small><em>Użytkownik
                      usunięty</em></small>{% else %}<small>@{{ recipe.username }}</small>{% endif %}
                  <br>
                  {{ recipe.description | truncate(50) }}
                </p>
              </div>
              <nav class="level is-mobile">
                <div class="level-left">
                  <a class="level-item">
                    <span class="icon is-small"><i class="fas fa-heart"></i></span>
                  </a>
                  <span style="margin-left: 3px">Wyświetleń: {{ recipe.views }}</span>
                </div>
              </nav>
            </div>
            <div class="media-right">
              <a class="button" href="{{ url_for('main.get_recipe', recipe_id=recipe.recipe_id) }}">Podgląd</a>
              <!-- <button class="button">Pobierz</button> -->
            </div>
          </article>
          {% endfor %}
        </article>
      </div>
      <div class="column is-one-third">
        <div class="column">

          <article class="panel is-link">
            <p class="panel-heading">
              Przepis dnia
            </p>
            <div class="panel-block">
              Codziennie inny losowy przepis.
            </div>

            <article class="media">
              <figure class="media-left">
                <p class="image is-128x128">
                  <img src="/static/img/logo.png">
                </p>
              </figure>
              <div class="media-content">
                <div class="content">
                  <p>
                    <a href="{{ url_for('main.get_recipe', recipe_id=daily_recipe.recipe_id) }}"
                      style="color: inherit"><strong>{{ daily_recipe.name }}</strong></a>
                    {% if daily_recipe.username is none %}
                    <small><em>Użytkownik usunięty</em></small>
                    {% else %}
                    <small>@{{ daily_recipe.username }}</small>
                    {% endif %}
                    <br>
                    {{ daily_recipe.description | truncate(25) }}
                  </p>
                </div>
              </div>
              <div class="media-right">
                <a class="button" href="{{ url_for('main.get_recipe', recipe_id=daily_recipe.recipe_id) }}">Podgląd</a>
                <!-- <button class="button">Pobierz</button> -->
              </div>
            </article>
          </article>


          <div class="column">
            <br>
          </div>




          <article class="panel is-info">


            <p class="panel-heading">
              Wyszukiwanie przepisu
            </p>

            <div class="tabs is-centered">


            </div>
            

            <div class="columns">

              <div class="column">
                <form method="GET" action="/szukaj">
                  <div class="control">
                    <input class="input" type="text" placeholder="Wyszukaj przepisu" name="q">
                  </div>
                  <div class="control">
                    <input class="input" type="hidden" name="typ" value="nazwa">
                  </div>
                  </br>
                  <div class="field">
                    <button class="button is-info is-rounded">Szukaj po nazwie</button>
                  </div>
                </form>
              </div>


              <div class="column">
                <form method="GET" action="/szukaj">
                  <div class="control">
                    <div class="select is-primary">
                      <select name="q">
                        {% for type in types_of_food %}
                        <option value="{{ type.name }}">{{ type.name }}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <div class="control">
                    <input class="input" type="hidden" name="typ" value="typ">
                  </div>
                  </br>
                  <div class="field is-centered">
                    <button class="button is-info is-rounded">Szukaj po typie</button>
                  </div>
                </form>
              </div>
              <div class="column">
                <form method="GET" action="/szukaj">
                  <div class="control">
                    <div class="select is-primary">
                      <select name="q">
                        {% for category in food_categories %}
                        <option value="{{ category.name }}">{{ category.name }}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="control">
                      <input class="input" type="hidden" name="typ" value="kategoria">
                    </div>
                  </div>
                  </br>
                  <div class="field">
                    <button class="button is-info is-rounded">Szukaj po kategorii</button>
                  </div>
                </form>
              </div>
            </div>
          </article>
        </div>



        <!--ostatnie przepisy-->
        <!--
      <article class="panel is-info">
        <p class="panel-heading">
          Ostatnie przepisy
        </p>
        <div class="panel-block">
        <div class="panel-block">
          <div class="tabs is-centered">
          </div>
        </div>
        </div>

        <article class="media">
          <figure class="media-left">
            <p class="image is-96x96">
              <img src="/static/img//logo.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Pierogi Pani Jadzi</strong> <small>@pania_jadzia</small>
                <br>
                Pyszne pierogi z malinami na chłodne wieczory.
              </p>
            </div>
          </div>
          <div class="media-right">
            <button class="button">podgląd</button>
          </div>
        </article>
        <article class="media">
          <figure class="media-left">
            <p class="image is-96x96">
              <img src="/static/img/logo.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Pierogi Pani Jadzi</strong> <small>@pania_jadzia</small>
                <br>
                Pyszne pierogi z malinami na chłodne wieczory.
              </p>
            </div>
          </div>
          <div class="media-right">
            <button class="button">podgląd</button>
          </div>
        </article>

        <article class="media">
          <figure class="media-left">
            <p class="image is-96x96">
              <img src="/static/img/logo.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Pierogi Pani Jadzi</strong> <small>@pania_jadzia</small>
                <br>
                Pyszne pierogi z malinami na chłodne wieczory.
              </p>
            </div>
          </div>
          <div class="media-right">
            <button class="button">podgląd</button>
          </div>
        </article>
        <article class="media">
          <figure class="media-left">
            <p class="image is-96x96">
              <img src="/static/img/logo.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Pierogi Pani Jadzi</strong> <small>@pania_jadzia</small>
                <br>
                Pyszne pierogi z malinami na chłodne wieczory.
              </p>
            </div>
          </div>
          <div class="media-right">
            <button class="button">podgląd</button>
          </div>
        </article>
        <article class="media">
          <figure class="media-left">
            <p class="image is-96x96">
              <img src="/static/img/logo.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Pierogi Pani Jadzi</strong> <small>@pania_jadzia</small>
                <br>
                Pyszne pierogi z malinami na chłodne wieczory.
              </p>
            </div>
          </div>
          <div class="media-right">
            <button class="button">podgląd</button>
          </div>
        </article>
        <article class="media">
          <figure class="media-left">
            <p class="image is-96x96">
              <img src="/static/img/logo.png">
            </p>
          </figure>
          <div class="media-content">
            <div class="content">
              <p>
                <strong>Pierogi Pani Jadzi</strong> <small>@pania_jadzia</small>
                <br>
                Pyszne pierogi z malinami na chłodne wieczory.
              </p>
            </div>
          </div>
          <div class="media-right">
            <button class="button">podgląd</button>
          </div>
        </article>
      -->

      </div>
    </div>
    <!--Stopka-->
    <footer class="footer">
      <div class="content has-text-centered">
        <p>
          <strong>WITKWINTNIE DANIE</strong>
        <p>Jakub Kulikowski, Adam Żywica, Adam Wasilewski, Piotr Sumiński, Piotr Król. </p>
        </br>
        <p>Projekt dostępny na,
          <a href="https://github.com/a-was/kuchniowy-raj">githubie</a>.
        </p>
        </p>
      </div>
    </footer>


</body>

</html>